---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# mxsrquick

<!-- badges: start -->
<!-- badges: end -->

The goal of mxsrquick is to is to make MixSIAR project run quicker

## Installation

You can install the development version of stepurr from [GitHub](https://github.com/) with:
```{r}
# install.packages("devtools")
# devtools::install_github("mncube/mxsrquick")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(mxsrquick)

#Create a dataframe which mimics isospace source data
iso_data <- data.frame(iso_a = c(2.2, 4.4, 3.3, 5.1, 3.4),
                       iso_b = c(1.6, 3.9, 5.2, 4.2, 3.7),
                       prot = c("bug", "bug", "bug", "plant", "plant"))

#Create an isospace plot using source groups' means and standard deviations
#Use tdf1 and tdf2 to correct for trophic discrimination factors
source_biplot(data = iso_data, group = prot, 
              var1 = iso_a, var2 = iso_b, 
              tdf1 = c(2, 1), tdf2 = c(1, 1),
              x_lab = "A", y_lab = "B")
```

